name: flutter_polyicon
description: One-shot icon font generator for Flutter. Convert SVG files to production-ready icon fonts with a single command.
version: 0.0.1
repository: https://github.com/wm-jenildgohel/flutter_polyicon
homepage: https://fluttericon.com

environment:
  sdk: '>=3.5.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  flutter:
    sdk: flutter
  collection: ^1.17.0
  dart_style: ^2.3.0
  logger: ^1.3.0
  meta: ^1.8.0
  path_parsing: ^1.0.1
  recase: ^4.1.0
  vector_math: ^2.1.4
  path: ^1.9.1
  xml: ^6.6.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  flutter_polyicon:
flutter:
  assets:
    - assets/poly_icons.png
