name: flutter_polyicon
description: One-shot icon font generator for Flutter. Convert SVG files to production-ready icon fonts with a single command.
version: 0.1.0
repository: https://github.com/ilikerobots/polyicon
homepage: https://fluttericon.com

environment:
  sdk: '>=3.5.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  icon_font_generator: ^4.0.0
  path: ^1.9.1
  xml: ^6.6.1
  yaml: ^3.1.3
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
